// This file is autogenerated by `script/convert.py`, 
// to edit it please use the `script/markers.txt` file thanks. 

UnminedCustomMarkers = {
    "isEnabled": true,
    "markers": [
        {
            "x": -138,
            "z": -864,
            "text": "Mooth's Legendary Tank",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 10px Verdana"
        },
        {
            "x": 21,
            "z": -151,
            "text": "XP Farm",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/xp.png",
            "imageScale": 0.25,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": 262,
            "z": -788,
            "text": "Creeper Farm",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana"
        },
        {
            "x": -240,
            "z": -200,
            "text": "Redz's Item Storage",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana"
        },
        {
            "x": 1472,
            "z": -494,
            "text": "End Portal (1)",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/eyeofender.png",
            "imageScale": 0.25,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": 4731,
            "z": 981,
            "text": "End Portal (2)",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/eyeofender.png",
            "imageScale": 0.25,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": -1454,
            "z": -1556,
            "text": "Trading Village (1)",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/emerald.png",
            "imageScale": 0.5,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": -81,
            "z": -195,
            "text": "Neko's Tunnel [In]",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 10px Verdana"
        },
        {
            "x": -57,
            "z": -854,
            "text": "Neko's Tunnel [Out]",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 10px Verdana"
        },
        {
            "x": -72,
            "z": -214,
            "text": "Main Spawn",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/dark.png",
            "imageScale": 0.5,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": -77,
            "z": -884,
            "text": "Neko's",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/custom/neko.png",
            "imageScale": 0.5,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": 120,
            "z": -856,
            "text": "Kagi's Base",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/custom/kagi.jpg",
            "imageScale": 0.5,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": -354,
            "z": -1100,
            "text": "Higashiyama-ku, Kyoto",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 12px Verdana",
            "image": "markers/custom/kyoto.png",
            "imageScale": 0.7,
            "imageAnchor": [
                0.5,
                1
            ]
        },
        {
            "x": -116,
            "z": -169,
            "text": "Mystia's Cuck Shed",
            "textColor": "#ffffff",
            "offsetX": 0,
            "offsetY": 8,
            "font": "bold 9px Verdana"
        }
    ]
}